# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../view.guide.ui/dash.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(763, 514)
        mainWindow.setMaximumSize(QtCore.QSize(763, 514))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_results = QtWidgets.QTableWidget(self.centralwidget)
        self.list_results.setGeometry(QtCore.QRect(20, 60, 721, 411))
        self.list_results.setObjectName("list_results")
        self.list_results.setColumnCount(7)
        self.list_results.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.list_results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_results.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_results.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_results.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_results.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_results.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_results.setHorizontalHeaderItem(6, item)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 20, 674, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.field_cpf = QtWidgets.QLineEdit(self.widget)
        self.field_cpf.setText("")
        self.field_cpf.setObjectName("field_cpf")
        self.horizontalLayout.addWidget(self.field_cpf)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.field_data_nascimento = QtWidgets.QLineEdit(self.widget)
        self.field_data_nascimento.setObjectName("field_data_nascimento")
        self.horizontalLayout.addWidget(self.field_data_nascimento)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cbbx_uf = QtWidgets.QComboBox(self.widget)
        self.cbbx_uf.setObjectName("cbbx_uf")
        self.cbbx_uf.addItem("")
        self.cbbx_uf.addItem("")
        self.cbbx_uf.addItem("")
        self.cbbx_uf.addItem("")
        self.cbbx_uf.addItem("")
        self.cbbx_uf.addItem("")
        self.horizontalLayout.addWidget(self.cbbx_uf)
        self.btn_consultar = QtWidgets.QPushButton(self.widget)
        self.btn_consultar.setObjectName("btn_consultar")
        self.horizontalLayout.addWidget(self.btn_consultar)
        # mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 763, 22))
        self.menubar.setObjectName("menubar")
        self.menuConfigurar = QtWidgets.QMenu(self.menubar)
        self.menuConfigurar.setObjectName("menuConfigurar")
        # mainWindow.setMenuBar(self.menubar)
        self.actionCredenciais = QtWidgets.QAction(mainWindow)
        self.actionCredenciais.setObjectName("actionCredenciais")
        self.actionSuporte = QtWidgets.QAction(mainWindow)
        self.actionSuporte.setObjectName("actionSuporte")
        self.actionFechar = QtWidgets.QAction(mainWindow)
        self.actionFechar.setObjectName("actionFechar")
        self.menuConfigurar.addAction(self.actionCredenciais)
        self.menuConfigurar.addAction(self.actionSuporte)
        self.menuConfigurar.addAction(self.actionFechar)
        self.menubar.addAction(self.menuConfigurar.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "DeepSearch - ClanSoftware"))
        item = self.list_results.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Registro"))
        item = self.list_results.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Nome"))
        item = self.list_results.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "CPF"))
        item = self.list_results.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Dt. Nasc."))
        item = self.list_results.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Celular"))
        item = self.list_results.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Telefoe"))
        item = self.list_results.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "Email"))
        self.label.setText(_translate("mainWindow", "CPF:"))
        self.label_2.setText(_translate("mainWindow", "Data de Nascimento"))
        self.label_3.setText(_translate("mainWindow", "UF"))
        self.cbbx_uf.setItemText(0, _translate("mainWindow", "Todos"))
        self.cbbx_uf.setItemText(1, _translate("mainWindow", "PR"))
        self.cbbx_uf.setItemText(2, _translate("mainWindow", "SC"))
        self.cbbx_uf.setItemText(3, _translate("mainWindow", "RS"))
        self.cbbx_uf.setItemText(4, _translate("mainWindow", "RJ"))
        self.cbbx_uf.setItemText(5, _translate("mainWindow", "SP"))
        self.btn_consultar.setText(_translate("mainWindow", "Consultar"))
        self.menuConfigurar.setTitle(_translate("mainWindow", "Configurar"))
        self.actionCredenciais.setText(_translate("mainWindow", "Credenciais"))
        self.actionSuporte.setText(_translate("mainWindow", "Suporte"))
        self.actionFechar.setText(_translate("mainWindow", "Fechar"))

